on: 
  push:
    branches:
      - 'master'
      - 'develop'
      - 'releases/**'
    tags:
    - v*.*.*
jobs: 
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to PYPI
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@v1.0.0a0
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
